### ISSUE TITLE
Appropriate stylesheet is missing border solid for line highlighting when not using TailwindCSS

### ISSUE THREAD

**Issue by jrson83** [timlrx/rehype-prism-plus#48]
The plugin is really great, but I don't use Next.js and the line highlighting `border-left` did not work for me at all. I tried to figure out why.

I checked out your website and the [Next.js starter](https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1#line-highlighting-and-line-numbers). Both using Tailwind CSS which in it's [preflight](https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally) resets `border-style` to `solid` for all elements. After inspecting both websites I see:

```css
*, ::after, ::before {
  box-sizing: border-box;
  border: 0 solid #e5e5e5;
}
```

I don't use tailwind, so I don't have `boder-style` set to `solid` and I don't see any of the line highlighting borders.

To fix this issue for people who not using Tailwind CSS, you should add `border-left-style: solid` to the `appropriate stylesheet`, for which you should now use the shorthand property "border-left" and also set the  color of the placeholder to `transparent`:

```css
.code-line {
  display: block;
  padding-left: 16px;
  padding-right: 16px;
  margin-left: -16px;
  margin-right: -16px;
  border-left: 4px solid transparent; /* Set code block color */
}

.highlight-line {
  margin-left: -16px;
  margin-right: -16px;
  background-color: rgba(55, 65, 81, 0.5); /* Set highlight bg color */
  border-left: 4px solid rgb(59, 130, 246); /* Set highlight accent border color */
}
```
